require('dotenv').config();
const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
const PORT=Number(process.env.PORT||10000),AF_KEY=process.env.API_FOOTBALL_KEY||'',FD_KEY=process.env.FOOTBALL_DATA_API_KEY||'';
const AF='https://v3.football.api-sports.io',FD='https://api.football-data.org/v4',LIVE_POLL_SECONDS=Math.max(30,Number(process.env.LIVE_POLL_SECONDS||90)),SYNC_MINUTES=Math.max(5,Number(process.env.SYNC_MINUTES||30));
const store={competitions:[],fixtures:[],slips:[],lastSync:null,providers:{}};const db=path.join(__dirname,'data-store.json');
const SA_NAMES=['Premier Soccer League','PSL','Betway Premiership','1st Division','Motsepe Foundation Championship','Nedbank Cup','Carling Knockout','League Cup'];
const AFRICA_NAMES=['CAF Champions League','CAF Confederation Cup','African Football League','Africa Cup of Nations','Africa Cup of Nations Qualification','African Nations Championship','CHAN'];
const now=()=>new Date().toISOString(),round=(n,d=4)=>Number(Number(n).toFixed(d)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function poisson(k,l){let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p}
function probs(h,a){let H=0,D=0,A=0;for(let i=0;i<8;i++)for(let j=0;j<8;j++){let p=poisson(i,h)*poisson(j,a);if(i>j)H+=p;else if(i===j)D+=p;else A+=p}let s=H+D+A||1;return{home:H/s,draw:D/s,away:A/s}}
function predict(f){let p=probs(1.35,1.05),mx=Math.max(p.home,p.draw,p.away),market=mx===p.home?'HOME_WIN':mx===p.away?'AWAY_WIN':'DRAW';let total=2.4,o25=1-(poisson(0,total)+poisson(1,total)+poisson(2,total)),btts=1-Math.exp(-1.35)-Math.exp(-1.05)+Math.exp(-total);return{probabilities:{home:round(p.home),draw:round(p.draw),away:round(p.away)},expectedGoals:{home:1.35,away:1.05},over25:round(o25),btts:round(btts),market,confidence:Math.round(clamp(mx*100,45,94)),risk:mx>=.8?'Low':mx>=.68?'Medium':'High'}}
async function get(url,headers,params){let q=new URLSearchParams(params||{}),r=await fetch(url+'?'+q,{headers});let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(r.status+': '+JSON.stringify(j));return j}
function normAF(x){let s=x.fixture?.status?.short||'NS',live=['1H','HT','2H','ET','BT','P','LIVE'].includes(s),h=x.teams?.home||{},a=x.teams?.away||{};let f={id:'apifb-'+x.fixture.id,provider:'api-football',providerFixtureId:x.fixture.id,utcDate:x.fixture.date,status:s,live,elapsed:x.fixture?.status?.elapsed||null,competition:{id:x.league?.id,name:x.league?.name||'Unknown',country:x.league?.country||'',type:x.league?.type||''},homeTeam:{id:'apifb-team-'+h.id,name:h.name||'Home',logo:h.logo||''},awayTeam:{id:'apifb-team-'+a.id,name:a.name||'Away',logo:a.logo||''},score:{home:x.goals?.home,away:x.goals?.away}};f.prediction=predict(f);return f}
function normFD(x){let s=x.status||'SCHEDULED',h=x.homeTeam||{},a=x.awayTeam||{},f={id:'fd-'+x.id,provider:'football-data',providerFixtureId:x.id,utcDate:x.utcDate,status:s,live:['IN_PLAY','PAUSED'].includes(s),competition:{id:x.competition?.id,name:x.competition?.name||'Unknown',country:x.area?.name||'',type:x.competition?.type||''},homeTeam:{id:'fd-team-'+h.id,name:h.name||'Home',logo:h.crest||''},awayTeam:{id:'fd-team-'+a.id,name:a.name||'Away',logo:a.crest||''},score:{home:x.score?.fullTime?.home,away:x.score?.fullTime?.away}};f.prediction=predict(f);return f}
function merge(a){let m=new Map();for(const f of a){let k=(f.homeTeam.name+'|'+f.awayTeam.name+'|'+f.utcDate).toLowerCase();if(!m.has(k)||f.provider==='api-football')m.set(k,f)}return [...m.values()].sort((a,b)=>new Date(a.utcDate)-new Date(b.utcDate))}
async function sync(){let all=[];if(AF_KEY){try{let r=await get(AF+'/fixtures',{'x-apisports-key':AF_KEY},{live:'all'});all.push(...(r.response||[]).map(normAF));store.providers.apiFootballLive={ok:true,count:(r.response||[]).length,at:now()}}catch(e){store.providers.apiFootballLive={ok:false,error:e.message,at:now()}}try{for(let i=0;i<3;i++){let d=new Date();d.setUTCDate(d.getUTCDate()+i);let r=await get(AF+'/fixtures',{'x-apisports-key':AF_KEY},{date:d.toISOString().slice(0,10),timezone:'Africa/Johannesburg'});all.push(...(r.response||[]).map(normAF))}store.providers.apiFootballUpcoming={ok:true,at:now()} }catch(e){store.providers.apiFootballUpcoming={ok:false,error:e.message,at:now()}}}if(FD_KEY){try{let a=new Date(),b=new Date();b.setUTCDate(b.getUTCDate()+9);let r=await get(FD+'/matches',{'X-Auth-Token':FD_KEY},{dateFrom:a.toISOString().slice(0,10),dateTo:b.toISOString().slice(0,10)});all.push(...(r.matches||[]).map(normFD));store.providers.footballData={ok:true,count:(r.matches||[]).length,windowDays:9,at:now()} }catch(e){store.providers.footballData={ok:false,error:e.message,windowDays:9,at:now()}}}if(all.length)store.fixtures=merge([...store.fixtures,...all]);store.lastSync=now();save()}
async function competitions(){let c=[];if(AF_KEY)try{let r=await get(AF+'/leagues',{'x-apisports-key':AF_KEY},{season:new Date().getUTCFullYear(),current:'true'});c=(r.response||[]).map(x=>({id:x.league.id,name:x.league.name,country:x.country?.name||'',type:x.league.type||'',logo:x.league.logo||'',coverage:x.coverage||{}}))}catch(e){store.providers.competitions={ok:false,error:e.message}}for(const n of SA_NAMES)if(!c.some(x=>x.name.toLowerCase().includes(n.toLowerCase())))c.push({id:'configured-'+n,name:n,country:'South Africa',type:'League/Cup',configured:true});for(const n of AFRICA_NAMES)if(!c.some(x=>x.name.toLowerCase().includes(n.toLowerCase())))c.push({id:'configured-'+n.replace(/\W+/g,'-'),name:n,country:'Africa',type:'Cup',configured:true});store.competitions=c.sort((a,b)=>a.name.localeCompare(b.name));save()}
function save(){try{fs.writeFileSync(db,JSON.stringify(store,null,2))}catch{}}try{Object.assign(store,JSON.parse(fs.readFileSync(db)))}catch{}
app.get('/health',(q,s)=>s.json({ok:true,version:'ULTRA-NEXT-GEN-PRO-PREDICTOR-31.1',lastSync:store.lastSync,providers:store.providers}));
app.get('/api/competitions',(q,s)=>{let a=store.competitions,x=String(q.query.q||'').toLowerCase();if(x)a=a.filter(c=>(c.name+' '+c.country+' '+c.type).toLowerCase().includes(x));s.json({count:a.length,data:a})});
app.get('/api/fixtures',(q,s)=>{let a=store.fixtures,m=q.query.mode||'all';if(m==='live')a=a.filter(f=>f.live);if(m==='upcoming')a=a.filter(f=>!f.live&&new Date(f.utcDate)>=new Date());if(m==='finished')a=a.filter(f=>!f.live&&new Date(f.utcDate)<new Date());if(q.query.q){let x=String(q.query.q).toLowerCase();a=a.filter(f=>(f.competition.name+' '+f.homeTeam.name+' '+f.awayTeam.name).toLowerCase().includes(x))}s.json({count:a.length,lastSync:store.lastSync,data:a})});
app.post('/api/refresh',async(q,s)=>{try{await competitions();await sync();s.json({ok:true,fixtures:store.fixtures.length,competitions:store.competitions.length,lastSync:store.lastSync})}catch(e){s.status(500).json({ok:false,error:e.message})}});
function durationEnd(v){const d=new Date();if(v==='24h')d.setHours(d.getHours()+24);else if(v==='3d')d.setDate(d.getDate()+3);else if(v==='7d')d.setDate(d.getDate()+7);else d.setHours(23,59,59,999);return d}
function marketOptions(f){const p=f.prediction?.probabilities||{};return [{market:'HOME_WIN',label:f.homeTeam.name,prob:p.home||0},{market:'DRAW',label:'Draw',prob:p.draw||0},{market:'AWAY_WIN',label:f.awayTeam.name,prob:p.away||0}].filter(x=>x.prob>0).sort((a,b)=>b.prob-a.prob)}
app.post('/api/slips/generate',(q,s)=>{try{
 const budget=Math.max(.01,Number(q.body.budget||1)),target=Math.max(budget,Number(q.body.target||150)),risk=['low','balanced','high'].includes(q.body.risk)?q.body.risk:'balanced';
 const end=durationEnd(q.body.duration||'today'),nowD=new Date(),thresholds={low:.78,balanced:.68,high:.58},maxLegs={low:5,balanced:8,high:10};
 const pool=store.fixtures.filter(f=>!f.live&&new Date(f.utcDate)>=nowD&&new Date(f.utcDate)<=end&&f.prediction);
 const ranked=pool.map(f=>({...f,best:marketOptions(f)[0]})).filter(x=>x.best&&x.best.prob>=thresholds[risk]).sort((a,b)=>b.best.prob-a.best.prob||b.prediction.confidence-a.prediction.confidence);
 const selected=[],usedTeams=new Set();for(const f of ranked){if(selected.length>=maxLegs[risk])break;const h=f.homeTeam.name.toLowerCase(),a=f.awayTeam.name.toLowerCase();if(usedTeams.has(h)||usedTeams.has(a))continue;selected.push(f);usedTeams.add(h);usedTeams.add(a)}
 const legs=selected.map(f=>({fixtureId:f.id,utcDate:f.utcDate,competition:f.competition.name,home:f.homeTeam.name,away:f.awayTeam.name,pick:f.best.market,selection:f.best.label,probability:round(f.best.prob),confidence:f.prediction.confidence,risk:f.prediction.risk}));
 const combined=legs.length?legs.reduce((x,l)=>x*l.probability,1):0,modelOdds=legs.length?round(1/combined,2):0,potentialReturn=round(budget*modelOdds,2);
 const slip={id:'SLIP-'+crypto.randomBytes(4).toString('hex').toUpperCase(),createdAt:now(),budget,target,duration:q.body.duration||'today',risk,legs,estimatedCombinedProbability:round(combined),estimatedOdds:modelOdds,potentialReturn,requiredOdds:round(target/budget,2),targetReached:potentialReturn>=target,source:'model-implied probability'};
 store.slips.unshift(slip);store.slips=store.slips.slice(0,100);save();s.json(slip);
}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/slips',(q,s)=>s.json({count:store.slips.length,data:store.slips}));
app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));
competitions().catch(()=>{});sync().catch(e=>console.error('Initial sync:',e.message));setInterval(()=>sync().catch(e=>console.error('Live sync:',e.message)),LIVE_POLL_SECONDS*1000);setInterval(()=>Promise.all([competitions(),sync()]).catch(()=>{}),SYNC_MINUTES*60000);
app.listen(PORT,'0.0.0.0',()=>console.log(`Ultra Next Gen Pro Predictor 31.1 listening on 0.0.0.0:${PORT} | live=${LIVE_POLL_SECONDS}s | sync=${SYNC_MINUTES}m | footballDataWindow=9d`));
