import express from 'express';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); app.use(express.json());
const PORT=process.env.PORT||3000, API='https://api.football-data.org/v4';
const storePath=path.join(__dirname,'data','store.json');
const read=()=>JSON.parse(fs.readFileSync(storePath,'utf8'));
const write=x=>fs.writeFileSync(storePath,JSON.stringify(x,null,2));
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const poisson=(k,l)=>Math.exp(-l)*Math.pow(l,k)/factorial(k); const factorial=n=>{let r=1;for(let i=2;i<=n;i++)r*=i;return r};
async function apiFetch(endpoint){ if(!process.env.FOOTBALL_DATA_API_KEY) throw new Error('FOOTBALL_DATA_API_KEY is not configured'); const r=await fetch(API+endpoint,{headers:{'X-Auth-Token':process.env.FOOTBALL_DATA_API_KEY}}); if(!r.ok) throw new Error(`Provider ${r.status}: ${await r.text()}`); return r.json(); }
function features(teamId,matches,venue){const h=matches.filter(m=>m.status==='FINISHED'&&((m.homeTeam.id===teamId&&venue!=='away')||(m.awayTeam.id===teamId&&venue!=='home'))).slice(-12); if(!h.length)return {gf:1.35,ga:1.35,ppg:1.2,n:0}; let gf=0,ga=0,pts=0; for(const m of h){const home=m.homeTeam.id===teamId, a=Number(m.score?.fullTime?.home??0),b=Number(m.score?.fullTime?.away??0); const f=home?a:b,g=home?b:a;gf+=f;ga+=g;pts+=f>g?3:f===g?1:0;} return {gf:gf/h.length,ga:ga/h.length,ppg:pts/h.length,n:h.length};}
function predict(m,history){const hf=features(m.homeTeam.id,history,'home'), af=features(m.awayTeam.id,history,'away'); const lg=Math.max(1.05,history.length?history.reduce((s,x)=>s+Number(x.score?.fullTime?.home??0)+Number(x.score?.fullTime?.away??0),0)/Math.max(1,history.length)/2:1.35); let lh=clamp((hf.gf*0.62 + (2-hf.ga)*0.38)*1.03,0.25,3.6), la=clamp((af.gf*0.62 + (2-af.ga)*0.38)*0.94,0.2,3.4); lh=lh*0.65+lg*0.35; la=la*0.65+lg*0.35; let hw=0,d=0,aw=0,o=0,btts=0; for(let i=0;i<=7;i++)for(let j=0;j<=7;j++){const p=poisson(i,lh)*poisson(j,la);if(i>j)hw+=p;else if(i===j)d+=p;else aw+=p;if(i+j>2)o+=p;if(i>0&&j>0)btts+=p;} const probs=[hw,d,aw].map(x=>x/(hw+d+aw)); const markets={HOME_WIN:probs[0],DRAW:probs[1],AWAY_WIN:probs[2],OVER_2_5:o,BTTS:btts}; const entries=Object.entries(markets).sort((a,b)=>b[1]-a[1]); const top=entries[0]; const entropy=-probs.reduce((s,p)=>s+(p? p*Math.log(p):0),0)/Math.log(3); const confidence=clamp(top[1]*(1-0.22*entropy)+(Math.min(hf.n,8)+Math.min(af.n,8))/16*0.05); return {matchId:m.id,home:m.homeTeam.name,away:m.awayTeam.name,kickoff:m.utcDate,competition:m.competition?.name,homeWin:probs[0],draw:probs[1],awayWin:probs[2],over25:o,btts:btts,expectedGoals:+(lh+la).toFixed(2),recommendedMarket:top[0],rawTopProbability:top[1],confidence,risk:confidence>=.7?'LOW':confidence>=.58?'MEDIUM':'HIGH',features:{home:hf,away:af},modelVersion:'UNGP-9.0-ensemble'};}
app.get('/api/health',(req,res)=>res.json({ok:true,model:'UNGP-9.0-ensemble',providerConfigured:Boolean(process.env.FOOTBALL_DATA_API_KEY),stored:read().matches.length}));
app.get('/api/matches',async(req,res)=>{try{const today=new Date(), from=req.query.dateFrom||today.toISOString().slice(0,10), to=req.query.dateTo||new Date(today.getTime()+3*86400000).toISOString().slice(0,10); const q=new URLSearchParams({dateFrom:from,dateTo:to}); if(req.query.competitions)q.set('competitions',req.query.competitions); const data=await apiFetch('/matches?'+q); const s=read(); for(const m of data.matches||[]){const i=s.matches.findIndex(x=>x.id===m.id);if(i>=0)s.matches[i]=m;else s.matches.push(m);} write(s); res.json({matches:data.matches||[]});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/predictions',async(req,res)=>{try{const data=await (async()=>{const t=new Date(),from=req.query.dateFrom||t.toISOString().slice(0,10),to=req.query.dateTo||new Date(t.getTime()+3*86400000).toISOString().slice(0,10);const q=new URLSearchParams({dateFrom:from,dateTo:to,status:'SCHEDULED'});if(req.query.competitions)q.set('competitions',req.query.competitions);return apiFetch('/matches?'+q)})(); const s=read(), history=s.matches.filter(x=>x.status==='FINISHED'); const ps=(data.matches||[]).map(m=>predict(m,history)); s.predictions=[...ps,...s.predictions].filter((x,i,a)=>a.findIndex(y=>y.matchId===x.matchId)===i).slice(0,2000); write(s); res.json({predictions:ps});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/sync',async(req,res)=>{try{const from=req.body.from,to=req.body.to;const q=new URLSearchParams({dateFrom:from,dateTo:to,status:'FINISHED'});if(req.body.competitions)q.set('competitions',req.body.competitions);const d=await apiFetch('/matches?'+q),s=read();for(const m of d.matches||[]){const i=s.matches.findIndex(x=>x.id===m.id);if(i>=0)s.matches[i]=m;else s.matches.push(m);}write(s);res.json({synced:d.matches?.length||0});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/strategy',async(req,res)=>{try{const {budget=100,stake=10,minConfidence=.62,maxSelections=5,risk='ALL'}=req.body;const t=new Date(),q=new URLSearchParams({dateFrom:t.toISOString().slice(0,10),dateTo:new Date(t.getTime()+3*86400000).toISOString().slice(0,10),status:'SCHEDULED'});const d=await apiFetch('/matches?'+q),s=read(),ps=(d.matches||[]).map(m=>predict(m,s.matches.filter(x=>x.status==='FINISHED'))).filter(p=>p.confidence>=Number(minConfidence)&&(risk==='ALL'||p.risk===risk)).sort((a,b)=>b.confidence-a.confidence).slice(0,Number(maxSelections));res.json({budget:Number(budget),plannedStake:Math.min(Number(budget),ps.length*Number(stake)),remaining:Math.max(0,Number(budget)-ps.length*Number(stake)),selections:ps});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/analytics',(req,res)=>{const s=read();res.json({matches:s.matches.length,predictions:s.predictions.length,finished:s.matches.filter(x=>x.status==='FINISHED').length,model:'UNGP-9.0-ensemble',dataQuality:s.matches.length>100?'GOOD':s.matches.length>30?'FAIR':'LOW'});});
app.use(express.static(path.join(__dirname,'public'))); app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`UNGP 9.0 running on ${PORT}`));
